import { cn } from "@workspace/ui/lib/utils"
import { getTierByLevel } from "../data/tiers"
import { CodeDisplay } from "./shared/code-display"
import { FaqAccordion  } from "./shared/faq-accordion"
import type {FaqItem} from "./shared/faq-accordion";

const TRADER_FAQS: Array<FaqItem> = [
  {
    q: "How is my fee discount applied?",
    a: "Your discount is applied automatically to every open and close fee when you have an active referral code. No additional action is required after setting the code.",
  },
  {
    q: "Can I change my referral code?",
    a: "Yes, you can update your referral code at any time. The new code's discount will apply going forward. Previous trades are not affected.",
  },
  {
    q: "Which fees get discounted?",
    a: "The discount applies to opening and closing fees on all perpetual positions. Funding rates and price impact are not affected by referral discounts.",
  },
  {
    q: "Where can I read more?",
    a: "Full referral program documentation, tier thresholds, and commission structures are available in the SO4 docs. Look under the Referrals section.",
  },
]

const AFFILIATE_FAQS: Array<FaqItem> = [
  {
    q: "When do I receive commissions?",
    a: "Commissions from your referrals' trading fees are distributed weekly, every Thursday. They are paid in USDC directly to your wallet.",
  },
  {
    q: "How are tiers determined?",
    a: "Your tier is based on the total trading volume generated by all your referrals in the past 30 days. Higher volume unlocks higher commission rates.",
  },
  {
    q: "Can I have multiple referral codes?",
    a: "Each address can register one referral code. All referrals under that code are attributed to the same affiliate address.",
  },
  {
    q: "What happens if a referral changes their code?",
    a: "If a referred user switches to a different code, future volume is attributed to the new code's affiliate. Past commissions already distributed are not affected.",
  },
]

type ExternalLinkProps = { href: string; children: React.ReactNode }

function ExternalLink({ href, children }: ExternalLinkProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center justify-between py-2.5 text-[12px] text-muted-foreground transition-colors hover:text-foreground"
    >
      {children}
      <svg
        width="12"
        height="12"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        className="shrink-0 opacity-50"
      >
        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
        <polyline points="15 3 21 3 21 9" />
        <line x1="10" y1="14" x2="21" y2="3" />
      </svg>
    </a>
  )
}

type Props = {
  tab: "traders" | "affiliates" | "distributions"
  traderCode: string | null
  affiliateCode: string | null
  traderDiscountPct: number
  affiliateTier: 1 | 2 | 3
}

export function ReferralsSidebar({
  tab,
  traderCode,
  affiliateCode,
  traderDiscountPct,
  affiliateTier,
}: Props) {
  const isAffiliate = tab === "affiliates" || tab === "distributions"
  const activeCode = isAffiliate ? affiliateCode : traderCode
  const tier = getTierByLevel(affiliateTier)
  const faqs = isAffiliate ? AFFILIATE_FAQS : TRADER_FAQS

  return (
    <aside className="flex w-72 shrink-0 flex-col gap-4 self-start lg:sticky lg:top-20">
      {/* Code section */}
      {activeCode ? (
        <>
          <CodeDisplay
            code={activeCode}
            label={isAffiliate ? "Your affiliate code" : "Active referral code"}
            onEdit={isAffiliate ? () => {} : undefined}
          />

          {/* Benefit badge */}
          <div className="rounded-xl border border-border bg-card p-4">
            {isAffiliate ? (
              <>
                <div className="mb-2 flex items-center gap-2">
                  <span
                    className={cn(
                      "inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold ring-1",
                      tier.colorClass,
                      tier.ringClass,
                    )}
                  >
                    {tier.label}
                  </span>
                  <span className="text-[11px] text-muted-foreground">
                    Tier {tier.level}
                  </span>
                </div>
                <p className="text-[12px] font-semibold text-foreground">
                  {tier.affiliateCommissionPct}% commission on referral fees
                </p>
                <p className="mt-0.5 text-[11px] text-muted-foreground">
                  Referees receive a {tier.traderDiscountPct}% fee discount.
                </p>
              </>
            ) : (
              <>
                <p className="text-[12px] font-semibold text-green-400">
                  You're receiving a {traderDiscountPct}% discount on your trades!
                </p>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  The reduced rate applies to every open and close fee.
                </p>
              </>
            )}
          </div>
        </>
      ) : (
        <div className="rounded-xl border border-dashed border-border bg-muted/10 p-4 text-center">
          <p className="text-[12px] font-medium text-muted-foreground">
            {isAffiliate ? "No affiliate code yet" : "No referral code active"}
          </p>
          <p className="mt-1 text-[11px] text-muted-foreground/60">
            {isAffiliate
              ? "Register a code to start earning commissions"
              : "Enter a code to get a fee discount"}
          </p>
        </div>
      )}

      {/* Quick links */}
      <div className="rounded-xl border border-border bg-card px-4 py-2">
        <div className="divide-y divide-border/50">
          {/* TODO: Replace # with actual docs URLs when documentation is published */}
          <ExternalLink href="#">How it works</ExternalLink>
          <ExternalLink href="#">Claiming rewards</ExternalLink>
          <ExternalLink href="#">Tiers</ExternalLink>
          <ExternalLink href="#">Transferring a referral code</ExternalLink>
        </div>
      </div>

      {/* FAQ */}
      <FaqAccordion items={faqs} />
    </aside>
  )
}
